const REACT_QUERY_DEFAULT_STALE_TIME = parseInt(process.env.REACT_QUERY_DEFAULT_STALE_TIME || '1000', 10);
const API_BASE_URL = process.env.API_BASE_URL;

export { REACT_QUERY_DEFAULT_STALE_TIME, API_BASE_URL };
